package com.slice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.slice.constants.TABLE_NAMES;
import lombok.Data;
import lombok.NoArgsConstructor;

import static com.slice.constants.TABLE_NAMES.JOB_CONFIGURATION;

/**
 * Created by Evegeny on 23/10/2016.
 */
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = JOB_CONFIGURATION)
public class JobConfiguration {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    private String id;

    private int numberOfWorkers;

    private String memoryOptions;

    private boolean expandable;

    private String functionName;

    private String language;

    private String codeVersion;

    private String cvsLink;

    private String dataInPath;

    private String dataOutPath;

    private String dataDropletLink;

    private int numberOfIndividuals;

    private double percentageMutate;

    private double percentageCrossover;

    private int numberOfGenerations;

    private double cutoffValues;



}
