package com.slice.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Created by Evegeny on 23/10/2016.
 */
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "PERSONS")
public class Person {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    private String id;
    private String name;
    private List<String> cities;

    public Person(String name) {
        this.name = name;
    }
}

